README.md
gatsby-node.js

fixes #6 
1. makes documentation clearer and less likely to make the error of not providing a query
2. rethrow errors of graphql
3. throw an error if there's no query

docs(query): make sure people use the right name

---

README.md

I've seen at least 3 or 4 repos with clear text admin API key, so this should be changed

docs(readme): advocate for dotenv usage

---

README.md

1. Add ALGOLIA_API_KEY to .env.
2. Use ALGOLIA_INDEX_NAME in configuration.

docs(README): add missing environment variables

---

.npmignore
package.json

As of `gatsby@2.12.1` (https://github.com/gatsbyjs/gatsby/pull/15284), we now parse GraphQL queries in dependencies to enable packages to ship queries! 
The examples in this repo however interfere with this and cause this package to break (details in https://github.com/gatsbyjs/gatsby/issues/15344) 
We highly recommend not shipping examples to `npm` and this PR fixes this by adding it to .npmignore
Cheers from the gatsby team!

Don't publish examples to npm

---

README.md

This is to silence prism highlighter warnings -- `env` is not on the list of [officially supported language tags](https://prismjs.com/#languages-list). Thanks!

chore: correct code block language tags

---

gatsby-node.js

This fixes #37 
Without the `await`, the `setSettings` call sometimes succeeded before the `moveIndex` and sometimes did not. This race condition caused irregular updates to indices.

add await to setSettings call

---

gatsby-node.js

The basic premise of this issue was that I kept getting an error saying `A replica index is already replica of another index` whenever I tried to pass queries into this plugin that contained a replicas array within their `settings` object. 
**I found that a solution was to prevent the plugin from trying to attach replica indices to a `_tmp` index.**
I also found that in `indexExists`, `error.status` needed to be switched to `error.statusCode`... apparently `error.status` was not returning an accurate status code...
I also found that `forwardToReplicas` was not supported... so, I implemented a quick solution to pass it through to Algolia. In the future, I'm assuming other modifiers will need to be added... So, I created an `extraModifiers` object to allow for additional property additions, …

Accounts for replica indices

---

.gitignore
example/gatsby-config.js
gatsby-node.js

Since it accepted the `objectID` not coming before, it started to receive an error in cases where the `objectID` was not passed from `version 0.8`.
I think this should be true even if the `objectID` is not correct to be managed by algolia.
It should also accept the default id bypassing the `objectID`.
For this, if the `objectID` or `id` is missing, I let it add normally without comparison. I also copied it to use it as an `objectID` if id came.
fixes #55

fix: allow "id" instead of "objectID" again

---

gatsby-node.js

Closes #52 (I hope)
This PR aims to fix an issue with the option `partialUpdates` enabled. Today, when the index doesn't exist the plugin, throws an error: "Index test_does_not_exist does not exist" because we can't browse on an index that doesn't exist.
One possible solution is to _force_ the creation of the index. We avoid more branches in the code and we follow the same logic when the index exists or doesn't exist. To force the creation of the index we use an empty `setSettings + waitTask` to ensure the index is created when we exit the function i.e. safe to browse. The index doesn't exist so the empty `setSettings` call shouldn't remove settings but create the index.
This change also fixes the issue described in https://github.com/algolia/gatsby-plugin-algolia/pull/60#issuecomment-6219 …

fix: return the index created

---

gatsby-node.js

When passing an async function, you will get the error
`TypeError: transformer(...).map is not a function`
which is correct becuse `Promise.map` is not a function.
Adding the parentheses will execute the async transformer,
and then apply `.map` to the array returned
Addesses issue: https://github.com/algolia/gatsby-plugin-algolia/issues/73

[fix] Fix async issue with transformer

---

gatsby-node.js

When only one query is configured, what people see is `Algolia: query 0: executing query` and it might make them think "zero query" has been executed.
Not sure between `#0` vs `#1`

chore: update message to clearly indicate the index of query

---

gatsby-node.js

closes #82
Previously, when using `enablePartialUpdates`, deleted records would not be removed from Algolia. It seems like this bug was caused by a very small typo which this PR fixes.

fix: remove deleted records

---

gatsby-node.js

In version 0.12.0, the `field` variable was undefined, which caused builds to fail. Defining the variable as I hope it was intended.

fix: define variable for fields check

---

README.md

In [v2.2.0](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/CHANGELOG.md#220-2019-03-19), Gatsby introduced `nodes` as a less verbose alternative to `edges { node }` in their GraphQL queries. See e.g. gatsbyjs/gatsby#21255 for details.

Update readme to use modern GraphQL query

---

gatsby-node.js

I'm submitting this because I reworked a decent amount of the plugin to be compatible with multiple queries to the same index. It seems to work well for my use case but the diff is fairly gnarly so I'm not sure if you'd like to pull this in or not. I'm happy to rework anything if you are interested in merging, but if not I can just maintain my fork and use the patched version for my needs. Let me know what you think, thanks!

feat(indexing): allow plugin to work with repeated single index in queries by batching

---

package.json

I ran into the same issue as #106 and think it might be better to specify the version of node this package requires in package.json. 
https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines

Specifiy what versions of node this package can build on

---

gatsby-node.js

This fixes an incorrect reference to the current object being parsed when used by the reporter.
Fixes #113

fix(indexing): reference correct object for partial update no match field log message (#113)

---

README.md
gatsby-node.js

- Fixes https://github.com/algolia/gatsby-plugin-algolia/issues/110, where existing index settings are completely replaced on indexing, even if you don't pass any settings in. Now your existing settings will only be replaced if you provide them.
- Adds note to the example in the README to clarify behavior.
I manually tested providing settings and not providing settings to make sure the behavior is correct now. I did not test anything around replicas, but I don't see any reason why that would be affected. From what I can tell the replicas feature currently only works if you provide settings in the plugin, because of the reliance on `settings.replicaUpdateMode`.

Fix index settings being wiped

---

package.json
yarn.lock

Yargs-parser has a prototype pollution vulnerability; the library is brought in as a transitive dependency by `gatsby-cli`.
This PR bumps the version of gatsby-cli; the library is also brought in by standard-version, but that's a dev dependency.
For more information on the vulnerability, see:
https://www.sourceclear.com/vulnerability-database/security/prototype-pollution/javascript/sid-22715
fixes https://github.com/algolia/gatsby-plugin-algolia/issues/119

chore(security): Update gatsby-cli to patch vulnerability in yargs-parser

---

gatsby-node.js
package.json
yarn.lock

Previously, when using `enablePartialUpdates` with `matchFields`, fields were compared using the `===` operator. This meant that objects and arrays would be flagged to be updated even if the contents of the objects and arrays were unchanged. This PR uses [`deep-equal`](https://github.com/inspect-js/node-deep-equal) to detect changes, so objects and arrays that have the same value would not trigger an unnecessary update.

feat: deep compare matchFields

---

gatsby-node.js
package.json

Hello, Gatsby maintainer here 👋 
While looking at the plugin I noticed that the `peerDependency` is set incorrectly. It should be a dependency on `gatsby` and not `gatsby-cli`. We're in the process of providing more helpful information on the `/plugins` page of our website and for that we need plugins to set their `peerDependencies` correctly/more specific.
I've also updated the minimum Node version as v3 requires at least 12.13.0.
Thanks!
Fixes https://github.com/algolia/gatsby-plugin-algolia/issues/123
Fixes https://github.com/algolia/gatsby-plugin-algolia/issues/126
Fixes https://github.com/algolia/gatsby-plugin-algolia/issues/97

fix: Correct `reporter` usage + set correct peerDep, engines

---

example/src/layouts/index.js

In [Gatsby v3](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#using-a-global-graphql-tag-for-queries) the graphql tag needs to be imported explicitly.

fix: import graphql tag explicitly

---

README.md
gatsby-node.js

This will let the build continue even if Algolia indexing fails.

feat: add continueOnError flag

---

example/package.json
example/yarn.lock
gatsby-node.js
package.json
yarn.lock

To update `algoliasearch` to the latest version, `4.9.1`, adapting the code per the [upgrade guide](https://www.algolia.com/doc/api-client/getting-started/upgrade-guides/javascript/) to take advantage of the latest improvements.
Not necessarily an issue, but letting this plugin rely on an outdated major certainly isn't ideal. Let me know what you think!
- Install deps from both the root package and the `example` package.
- Create a brand new app on Algolia and open its indices page. It shouldn't have any indices (in case you followed this step)
- Set up your credentials on the `.env.production` on the `example` package.
- Run `yarn build` on the `example` package.
- Now refresh the indices page. You should see the pages from the `example` app there.
You can also take a look at one of my …

Migrate to algoliasearch@4.x

---

example/gatsby-config.js
gatsby-node.js

There were a couple issues with the code related to #150 .  This PR fixes both.
- Fixed `indexExists` function to check for HTTP status code under the `error.status` property rather than `error.statusCode`
- Creating `index` if it doesn't exist _every time_ since we always want it to be created if it does not exist.  There are several places in the code that blow up if the index does not exist.

Fix #150 - Creates index if it does not exist

---

package.json

This simply adds version 4 to the `gatsby` peer dependencies. I've done some basic testing on my existing site with this and it appears to work fine with no additional changes required.

Allow installation with Gatsby 4

---

gatsby-node.js

- Every once in a while the indexed products in Algolia would disappear completely.
- We contacted Algolia and after their investigation, they responded that the problem was within the plugin.
- The trigger was when there were multiple deploy processes.
"What happened this time is that you had multiple hosts executing these steps in parallel.
- Host A sent records to the `dev_NAME_tmp` index, which was created at this point.
- Host A updated index setting of the `dev_NAME_tmp` index.
- Host B sent records to the `dev_NAME_tmp` index.
- Host A renamed `dev_NAME_tmp` to `dev_NAME`.
- Host B updated the index setting of the dev_NAME_tmp index. This creates NEW `dev_NAME_tmp` without records.
- Host A renamed `dev_NAME_tmp` to `dev_NAME` again, which eventually overwrote the production index …

fix: avoid indexes to get empty copies when multiple builds are happening

---

README.md
gatsby-node.js

The `mergeSettings` option will merge whatever settings you have with the existing index settings.  The settings defined for the query will take precedence.
This allows you to make index changes using the Algolia web interface and to preserve those changes.  Currently, any changes you make through the Algolia web interface are overwritten anytime this plugin runs.

Adding merge settings option

---

README.md
gatsby-node.js

We're using a corporate proxy and cannot make `gatsby-plugin-algolia` work without passing a custom requester.
I found this PR (https://github.com/algolia/algoliasearch-client-javascript/pull/1180) where `createNodeHttpRequester` was extended to pass a custom HTTP agent.
With this change you can pass an optional custom requester to `gatsby-plugin-algolia` which resolved our issue.
Feedback is welcome. Let me know if I still need to change/add something. 
Thanks in advance!
Bart (from 🇧🇪)

feat(config): Allow options to be passed to algoliasearch
